apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - project_variables.yaml
  - secret-fernet-key.yaml
  - secret-postgres-credentials.yaml
  - secret-redis-password.yaml
  - secret-webserver-key.yaml