kind: ConfigMap
apiVersion: v1
metadata:
  name: airflow-cluster-project-variables
data:
  # Configuration values can be set as key-value properties
  project_name: "<YOUR_PROJECT_ID>"
  location: "europe-west1"
  navbar_color: "#FFA500"
  bucket: "<YOUR_BUCKET_NAME>"
